version: '3'
services:
  app:
    build: .
    container_name: projeto01
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - minha_rede
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: appdb
      DB_USERNAME: user
      DB_PASSWORD: vvv

  db:
    image: mysql:8
    container_name: appdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: vvv
    networks:
      - minha_rede

networks:
  minha_rede:
    driver: bridge
